name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: ./configure
    - name: make
      run: make 3_Implementation/
    - name: make check
      run: make check 3_Implementation/
    - name: make distcheck
      run: make distcheck 3_Implementation/
