# This is a basic workflow to help you get started with Actions

name: Contribution Check - Git Inspector

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  inspect:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      # Runs a single command using the runners shell
      - name: Install python
        run: sudo apt -y install python

      # Runs a set of commands using the runners shell
      - name: Install gitinspector
        run: |
            pushd ~ &> /dev/null
            git clone --depth=1 https://github.com/ejwa/gitinspector.git
            cd gitinspector
            echo "export PATH=$(pwd):"'$PATH' >> ~/.profile
            popd &> /dev/null

      - name: Run gitinspector
        run: |
          source ~/.profile
          export PYTHONIOENCODING=utf-8
          gitinspector.py --version
          echo "Running for commit : $GITHUB_SHA"
          echo "============ Git Inspector ==========="
          gitinspector.py -wTHl --format=text -f c,h,md,yml,* -x file:Project/3_Implementation/unity -x file:doc .
          gitinspector.py -wTHl --format=html -f c,h,md,yml,* -x file:Project/3_Implementation/unity -x file:doc . > ~/result.html
          echo "======================================"
